run:
  skip-dirs:
    - responses

output:
  sort-results: true

linters:
  disable:
    - cyclop
    - dupl # (duplicate code)
    - funlen # (func length)
    - varnamelen

    # deprecated with replacement
    - nosnakecase # (revive)
    - maligned # (fieldalignment)
    - scopelint # (exportloopref)
    - golint # (revive)
    - deadcode # (unused)
    - varcheck # (unused)
    - exhaustivestruct # (exhaustruct)
    
    # deprecated without replacement
    - interfacer
    - ifshort
    
    # generics
    - structcheck
  enable-all: true